# Generated by Django 4.2.5 on 2023-09-11 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_personal_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal_Details',
            new_name='Info',
        ),
    ]
