# Generated by Django 4.2.5 on 2023-09-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_rename_personal_details_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
